bitbucket
fair-software/howfairis pull request #157
Opened 2021-02-05 23:46 UTC by jspaaks

Added bitbucket suppport including some simple tests. Refs #52 

This PR includes a couple other PRs (#156, #154, #146), so be mindful before merging

2021-02-09 14:06 UTC, sverhoeven requested changes
Running against bitbucket or heptapod URLs gives expected compliance.

```shell
howfairis http://bitbucket.org/jspaaks/badge-test
howfairis https://bitbucket.org/verhoes/amifair
howfairis https://bitbucket.org/bitbucketpipelines/bitbucket-pipes-toolkit
howfairis https://foss.heptapod.net/mercurial/mercurial-bitbucketize
```

When platform does not match we should raise an exception ourselves instead of returning None and having later code raise a weird error.

For heptapod tests created #184

2021-02-09 14:06 UTC, sverhoeven commented on howfairis/mixins/license_mixin.py
> +            r = False
Spinned of https://github.com/fair-software/howfairis/issues/183 to see if LICENSE file is present

2021-02-10 09:45 UTC, jspaaks commented on howfairis/mixins/license_mixin.py
> +                .find(string="No license. All rights reserved") is None
Can do, but I'd prefer to let the development be guided by the feedback we will be getting from SonarCloud. That will help take out ambiguity about what is or isnt a good pattern.

2021-02-10 09:47 UTC, sverhoeven commented on howfairis/mixins/license_mixin.py
> +                .find(string="No license. All rights reserved") is None
Agree, let's use the duplicate code warnings from SonarCloud.

2021-02-10 09:59 UTC, jspaaks commented on howfairis/vcs_platform.py
> +    HEPTAPOD = auto()
I don't think this is the correct place for writing down that information. BTW if you go to foss.heptapod.net, it says "GitLab" at the top and looks basically like GitLab, so perhaps that's enough indication?

2021-02-10 10:01 UTC, jspaaks commented on tests/bitbucket/jspaaks/badge_test/mocker.py
> +        m.get("http://bitbucket.org/jspaaks/badge-test")
Good catch on that https. I noticed this behavior as well, https://github.com/fair-software/howfairis/pull/171#issue-569684431, I think I know how to solve this. The problem is that we're making requests outside the mocker context, hence howfairis just goes online and does its thing. I will continue this work in the other PR, not here.

2021-02-10 11:37 UTC, sverhoeven commented on howfairis/vcs_platform.py
> +    HEPTAPOD = auto()
OK, created https://github.com/fair-software/howfairis/issues/193 to have heptapod mentioned in the docs.

2021-02-10 19:30 UTC, jspaaks commented on howfairis/vcs_platform.py
> +    HEPTAPOD = auto()
Added this to `cli`'s information string and in the README.rst

2021-02-11 07:34 UTC, sverhoeven approved these changes
All my suggestions where applied or delayed to other issues.

2021-02-11 15:16 UTC, jspaaks commented
During the planning we put this PR out of scope for 0.13.0, where do we stand on that now?

2021-02-15 10:07 UTC, sverhoeven commented
We will keep it out of scope for 0.13.0

2021-03-03 15:31 UTC, fdiblen commented
Can we close this?

2021-03-04 12:19 UTC, jspaaks commented
Closing is fine with me, it's now probably more work to sync this than to start anew.

2021-03-04 12:19 UTC, closed without merging