Create PULL_REQUEST_TEMPLATE.md
fair-software/howfairis pull request #187
Opened 2021-02-09 15:01 UTC by fdiblen

Adds a pull request template

2021-02-09 15:57 UTC, sverhoeven requested changes
Content looks good to me.

At https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository lowercase is used for filename. 

Uppercase probably also works, but I think it is better to follow the docs. Can you rename the file to `.github/pull_request_template.md`?

2021-02-09 17:28 UTC, jspaaks commented on .github/PULL_REQUEST_TEMPLATE.md
> +## Instructions to review the pull request
I prefer to not shout big captions at whoever makes the pull request, just boldface is enough

```suggestion
**List of related issues or pull requests**

Refs: #ISSUE_NUMBER

**Describe the changes made in this pull request**

**Instructions to review the pull request**
```

2021-02-09 17:41 UTC, jspaaks approved these changes
:trophy: :8ball:

2021-02-10 08:34 UTC, sverhoeven approved these changes
Nice

2021-02-10 08:53 UTC, merged