Update README.dev.rst
fair-software/howfairis pull request #283
Opened 2021-02-19 12:14 UTC by jspaaks

**List of related issues or pull requests**

Refs: #261

**Describe the changes made in this pull request**

Updated docker build instructions

**Instructions to review the pull request**

[README.dev.rst](README.dev.rst)

2021-02-22 14:58 UTC, fdiblen commented on README.dev.rst
>      docker build -t fairsoftware/howfairis .
```suggestion
    docker build -t fairsoftware/howfairis:latest .
```

2021-02-22 14:59 UTC, fdiblen commented on README.dev.rst
> +    docker push fairsoftware/howfairis:${VERSION}
```suggestion
    docker push fairsoftware/howfairis:${VERSION}
    docker push fairsoftware/howfairis:latest    
```

2021-02-22 15:01 UTC, fdiblen requested changes
I proposed very minor changes. Thanks @jspaaks :fish:

2021-02-25 12:33 UTC, fdiblen approved these changes
Good to go! :1234:

2021-02-25 12:34 UTC, jspaaks commented
Thanks for the suggestions

2021-02-25 12:34 UTC, merged